### PR TITLE
projects.yml: add box-cli-maker project

### PR DESCRIPTION
**Pull request by Delta456**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/india/blob/main/CONTRIBUTING.md>.

### Which change are you proposing?

  - [x] Adding/updating open source project/s
  - [ ] Adding/updating maintainer/s
  
---

### Adding/updating open source project/s

- [x] The project was built in or receives significant contributions from India
- [x] The project has at least 100 stargazers

**Why should this open source project be featured?**

> Make Highly Customized Boxes in CLI. Notably used by [kubernetes/minikube](https://github.com/kubernetes/minikube/blob/master/go.mod#L8). Other importers can be found [here](https://pkg.go.dev/github.com/Delta456/box-cli-maker/v2?tab=importedby)

### Adding/updating maintainer/s

- [x] Maintainer's location on their GitHub profile indicates as India
- [x] Maintainer has approved this PR to be included on the website

**What open source project/s does the individual maintain?**

> https://github.com/Delta456/box-cli-maker

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing page, or at least not a single one

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by Delta456** [comment]
Merge conflict fixed, can be reviewed!

**Review by mvkaran — CHANGES_REQUESTED** [review]
Thanks for your contribution @Delta456 💙 

The project would largely fit into the "Developer Productivity & Tools" category itself, rather than warranting a new "Terminal" category currently. Can you please change the category?

**Comment by Delta456** [comment]
> Thanks for your contribution @Delta456 💙
> 
> The project would largely fit into the "Developer Productivity & Tools" category itself, rather than warranting a new "Terminal" category currently. Can you please change the category?

Done

**Review by mvkaran — APPROVED** [review]
Thanks!

**Comment by Delta456** [comment]
> Thanks!

I should be thankful to your team who started this initiative 🙂

**Pull request merged**
