### PR TITLE
Update GCP-India.md

### PR DESCRIPTION
**Pull request by iAmVickster**
kindly add my institution to your list.

### CODE REVIEW

**Comment by arkodyuti** [comment]
Hi @iAmVickster 👋🏻 GitHub 🇮🇳 Externship is open to GitHub Campus Program institutions only. You can ask your institution faculty/HoD check the eligibility and apply here: https://education.github.com/schools .Thanks 😊

**Review by Siddhant-K-code — COMMENTED** [review]
This thing can't be done through PR.
This File gets updates from GitHub India Team.

To become a GitHub Campus Program partner school, go to this  [GitHub Education - Schools Page](https://education.github.com/schools)

You Need to Ask your college's professor/HOD/Admin to apply and complete the remaining formalities. It is completely free, as a student most you can do to convince your professor regarding it, and how GitHub Education can help students.

**Comment by iAmVickster** [comment]
Thank you for your response.
Can I please know what is the deadline?

**Comment by Siddhant-K-code** [comment]
14 th December to apply for externships 2021. Btw you can start your application got github campus partner school program so that you will ve eligible next time.

**Comment by iAmVickster** [comment]
Thanks a lot. Sure Will do that.

**Pull request closed without merging**
