### PR TITLE
Add amitmerchant1990

### PR DESCRIPTION
**Pull request by amitmerchant1990**
### Please confirm this pull request meets the following requirements:

- [✔] I followed the contributing guidelines: <https://github.com/github/india/blob/main/CONTRIBUTING.md>.

### Which change are you proposing?

  - [ ] Adding/updating open source project/s
  - [✔] Adding/updating maintainer/s
  
---

### Adding/updating maintainer/s

- [✔] Maintainer's location on their GitHub profile indicates as India
- [✔] Maintainer has approved this PR to be included on the website

**What open source project/s does the individual maintain?**

> [markdownify](https://github.com/amitmerchant1990/electron-markdownify), [reverie](https://github.com/amitmerchant1990/reverie), [pomolectron](https://github.com/amitmerchant1990/pomolectron), [notepad](https://github.com/amitmerchant1990/notepad)

### CODE REVIEW

**Review by mvkaran — APPROVED** [review]
Thanks for your contribution @amitmerchant1990 💙

**Comment by amitmerchant1990** [comment]
@mvkaran when will the changes reflect on the website?

**Comment by mvkaran** [comment]
@amitmerchant1990 The changes have landed on the website 🎉

**Comment by amitmerchant1990** [comment]
That's great! Thanks! :)

**Pull request merged**
