### PR TITLE
Added Akhil G Krishnan to kerala maintainer list

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/india/blob/main/CONTRIBUTING.md>.

### Which change are you proposing?

  - [ ] Adding/updating open source project/s
  - [x] Adding/updating maintainer/s
  
---

### Adding/updating open source project/s

- [ ] The project was built in or receives significant contributions from India
- [ ] The project has at least 100 stargazers

**Why should this open source project be featured?**

> Please replace this line with an explanation of why you think these changes should be made.

### Adding/updating maintainer/s

- [x] Maintainer's location on their GitHub profile indicates as India
- [ ] Maintainer has approved this PR to be included on the website

**What open source project/s does the individual maintain?**

> https://github.com/saeloun/miru-web
> https://github.com/rails/rails
> https://github.com/chatwoot/chatwoot
> https://github.com/ToolJet/ToolJet

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing page, or at least not a single one

> Added my name to the kerala maintainer list.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by akhilgkrishnan** [comment]
cc: @mvasirani

**Comment by mvkaran** [comment]
Thanks for your contribution @akhilgkrishnan 💙 

Unfortunately, we won't be able to accept your PR. While I can see you are a contributor to rails, chatwoot, and Tooljet, we are currently only listing maintainers of projects.

miru-web seems like a promising project. However, we are currently listing maintainers whose projects have a significant traction in the community.

If you feel this is an error, feel free to open a new PR.

All the best in your open source journey!

**Comment by akhilgkrishnan** [comment]
Hi @mvkaran,
Miru-web is a growing project and its maintained by a lot for developers. And it also listed in the ProductHunt https://www.producthunt.com/products/miru-time-tracking-invoicing-benefits

**Comment by mvkaran** [comment]
Hi @akhilgkrishnan,
Great to hear that miru-web is growing! 

However, I believe there's still a great opportunity for the project to grow. Once the requirements in #932 gets fulfilled, we'd be happy to review adding you and miru-web to the listing.

All the best!

**Pull request closed without merging**
